extends Node

# this could be a Resource instead of a Node, but I prefer working with nodes, because I can see them in the node tree near where they're needed.

@export var beginner_words = {
		"freeze":["frame","thaw","crystalize"],
		"destroy":["create","preserve","transmute"],
		"order":["chaos","balance","harmony"],
		"consume":["produce","share","recycle"],
		"obey":["rebel","question","understand"],
		"divide":["unite","separate","integrate"],
		"control":["freedom","influence","cooperate"],
		"win":["lose","compete","collaborate"],
		"survive":["live","adapt","thrive"],
		"power":["weakness","responsibility","compassion"],
		"logic":["emotion","reason","intuition"],
		"certainty":["doubt","confidence","curiosity"],
		"self":["other","identity","connection"],
		"learn":["teach","study","explore"],
		"play":["work","fun","challenge"],
		"love":["hate","care","passion"],
		"build":["destroy","improve","innovate"],
		"collect":["discard","share","organize"],
		"protect":["attack","defend","support"],
		"lead":["follow","inspire","collaborate"],
		"change":["stay","grow","adapt"],
		"trust":["distrust","believe","verify"],
		"help":["harm","assist","empower"],
		"heal":["hurt","cure","transform"],
		"express":["suppress","communicate","create"],
		"choose":["reject","decide","evaluate"],
		"discover":["hide","reveal","investigate"],
		"remember":["forget","recall","reflect"],
		"dream":["wake","imagine","realize"],
		"hope":["fear","wish","act"],
		"solve":["create","understand","optimize"],
		"relax":["stress","rest","enjoy"],
		"laugh":["cry","smile","empathize"],
		"clean":["dirty","tidy","sanitize"],
		"fast":["slow","quick","efficient"],
		"happy":["sad","joyful","content"],
		"hot":["cold","warm","spicy"],
		"big":["small","large","important"],
		"red":["green","crimson","blood"],
		"fly":["fall","soar","travel"],
		"light":["dark","bright","energy"],
		"hard":["easy","solid","difficult"],
		"soft":["hard","smooth","gentle"],
		"sharp":["dull","pointed","smart"],
		"round":["square","circular","whole"],
		"high":["low","tall","elevated"],
		"deep":["shallow","profound","submerged"],
		"long":["short","lengthy","enduring"],
		"loud":["quiet","noisy","intense"],
		"sweet":["sour","sugary","pleasant"],
		"young":["old","youthful","new"],
		"rich":["poor","wealthy","abundant"],
		"simple":["complex","easy","clear"],
		"open":["closed","wide","honest"],
		"strong":["weak","powerful","resilient"],
		"black":["white","dark","mystery"],
		"smooth":["rough","sleek","calm"],
		"clear":["unclear","transparent","obvious"],
		"thick":["thin","dense","viscous"],
		"wet":["dry","moist","drenched"],
		"near":["far","close","adjacent"],
		"begin":["end","start","commence"],
		"old":["new","aged","vintage"],
		"poor":["rich","destitute","scarce"],
		"fasten":["unfasten","secure","tie"],
		"cheap":["expensive","inexpensive","low-priced"],
		"expand":["contract","extend","widen"],
		"dark":["light","dim","gloomy"],
		"quiet":["loud","silent","serene"],
		"calm":["agitated","relaxed","composed"],
		"rough":["smooth","coarse","unpolished"],
		"arrive":["depart","reach","show up"],
		"accept":["reject","approve","agree"],
		"attack":["defend","assault","strike"],
		"beautiful":["ugly","attractive","pretty"],
		"beginning":["ending","start","commencement"],
		"bold":["timid","courageous","brave"],
		"careful":["careless","cautious","prudent"],
		"dangerous":["safe","hazardous","risky"],
		"day":["night","dawn","morning"],
		"empty":["full","vacant","unfilled"],
		"failure":["success","defeat","loss"],
		"give":["take","offer","provide"],
		"ignorant":["knowledgeable","unaware","uninformed"],
		"inside":["outside","interior","indoors"],
		"junior":["senior","younger","subordinate"],
		"knowledge":["ignorance","wisdom","information"],
		"maximum":["minimum","greatest","highest"],
		"nearby":["distant","close","adjacent"],
		"present":["absent","current","existent"],
		"question":["answer","inquiry","interrogation"],
		"single":["married","unmarried","sole"],
		"top":["bottom","peak","summit"],
		"up":["down","above","ascend"],
		"victory":["defeat","success","triumph"],
		"weak":["strong","feeble","frail"],
		"brave": ["cowardly", "courageous", "fearless"],
		"friend": ["enemy", "companion", "pal"],
		"break": ["fix", "shatter", "crack"],
}

@export var intermediate_words = {
		"obfuscate": ["clarify", "confuse", "bewilder"],
		"ineffable": ["utterable", "indescribable", "inexpressible"],
		"ebullient": ["dejected", "exuberant", "effervescent"],
		"ersatz": ["genuine", "artificial", "substitute"],
		"soporific": ["stimulating", "drowsy", "sedative"],
		"quixotic": ["practical", "impractical", "idealistic"],
		"pulchritudinous": ["ugly", "beautiful", "attractive"],
		"effulgent": ["dim", "radiant", "glowing"],
		"vicissitude": ["stability", "change", "fluctuation"],
		"jejune": ["mature", "immature", "naive"],
		"mellifluous": ["grating", "melodious", "soothing"],
		"sesquipedalian": ["concise", "verbose", "long-winded"],
		"antediluvian": ["contemporary", "prehistoric", "ancient"],
		"flibbertigibbet": ["serious", "frivolous", "flighty"],
		"quidnunc": ["ignoramus", "gossip", "busybody"],
		"amour": ["hate", "love", "passion"],
		"ennui": ["interest", "boredom", "apathy"],
		"joie de vivre": ["sorrow of life", "joy of living", "zest for life"],
		"cul-de-sac": ["thoroughfare", "dead end", "impasse"],
		"soufflé": ["deflated", "puffed", "inflated"],
		"odio": ["love", "hate", "disgust"],
		"esperanza": ["despair", "hope", "optimism"],
		"amigo": ["enemy", "friend", "comrade"],
		"casa": ["apartment", "house", "home"],
		"gracias": ["blame", "gratitude", "appreciation"],

}


@export var advanced_words = {
		"爱": ["hate", "love", "emotion"],
		"幸福": ["unhappiness", "happiness", "bliss"],
		"友谊": ["enmity", "friendship", "camaraderie"],
		"家": ["outside", "home", "dwelling"],
		"成功": ["failure", "success", "victory"],
		"困难": ["easy", "difficulty", "challenge"],
		"和平": ["war", "peace", "harmony"],
		"进步": ["regress", "progress", "development"],
		"自由": ["restraint", "freedom", "independence"],
		"希望": ["despair", "hope", "expectation"],
		"一 (yī)": ["many", "one", "single"],
		"二 (èr)": ["none", "two", "double"],
		"三 (sān)": ["few", "three", "triple"],
		"四 (sì)": ["zero", "four", "quadruple"],
		"五 (wǔ)": ["rare", "five", "quintuple"],
		"六 (liù)": ["abundant", "six", "sextuple"],
		"七 (qī)": ["few", "seven", "septuple"],
		"八 (bā)": ["many", "eight", "octuple"],
		"九 (jiǔ)": ["scarce", "nine", "nonuple"],
		"十 (shí)": ["zero", "ten", "decuple"],
		"白 (bái)": ["black", "white", "clear"],
		"黑 (hēi)": ["white", "black", "dark"],
		"高 (gāo)": ["low", "high", "tall"],
		"矮 (ǎi)": ["tall", "short", "low"],
		"大 (dà)": ["small", "big", "great"],
		"小 (xiǎo)": ["big", "small", "little"],
		"长 (cháng)": ["short", "long", "lengthy"],
		"短 (duǎn)": ["long", "short", "brief"],
		"多 (duō)": ["few", "many", "much"],
		"少 (shǎo)": ["many", "few", "little"],
		"快 (kuài)": ["slow", "fast", "quick"],
		"慢 (màn)": ["fast", "slow", "sluggish"],
		"新 (xīn)": ["old", "new", "fresh"],
		"旧 (jiù)": ["new", "old", "worn"],
		"好 (hǎo)": ["bad", "good", "fine"],
		"坏 (huài)": ["good", "bad", "spoiled"],
		"难 (nán)": ["easy", "difficult", "hard"],
		"易 (yì)": ["difficult", "easy", "simple"],
		"贵 (guì)": ["cheap", "expensive", "valuable"],
		"便宜 (piányi)": ["expensive", "cheap", "inexpensive"],
		"忙 (máng)": ["leisurely", "busy", "occupied"],
		"闲 (xián)": ["busy", "leisurely", "idle"],
		"胖 (pàng)": ["thin", "fat", "plump"],
		"瘦 (shòu)": ["fat", "thin", "lean"],
		"远 (yuǎn)": ["near", "far", "distant"],
		"近 (jìn)": ["far", "near", "close"],
		"前 (qián)": ["back", "front", "previous"],
		"喜欢 (xǐhuān)": ["dislike", "like", "enjoy"],
		"讨厌 (tǎoyàn)": ["like", "dislike", "hate"],
		"高兴 (gāoxìng)": ["sad", "happy", "glad"],
		"伤心 (shāngxīn)": ["happy", "sad", "heartbroken"],
		"快乐 (kuàilè)": ["unhappy", "happy", "joyful"],
		"难过 (nánguò)": ["happy", "sad", "upset"],
		"容易 (róngyì)": ["difficult", "easy", "simple"],
		"困难 (kùnnán)": ["easy", "difficult", "challenging"],
		"简单 (jiǎndān)": ["complex", "simple", "easy"],
		"复杂 (fùzá)": ["simple", "complex", "complicated"],
		"安静 (ānjìng)": ["noisy", "quiet", "calm"],
		"吵 (chǎo)": ["quiet", "noisy", "loud"],
		"漂亮 (piàoliang)": ["ugly", "beautiful", "pretty"],
		"丑 (chǒu)": ["beautiful", "ugly", "plain"],
		"帅 (shuài)": ["plain", "handsome", "good-looking"],
		"强壮 (qiángzhuàng)": ["weak", "strong", "powerful"],
		"虚弱 (xūruò)": ["strong", "weak", "frail"],
		"勇敢 (yǒnggǎn)": ["cowardly", "brave", "courageous"],
		"胆小 (dǎnxiǎo)": ["brave", "cowardly", "timid"],
		"愿意 (yuànyì)": ["unwilling", "willing", "ready"],
		"不愿意 (bù yuànyì)": ["willing", "unwilling", "reluctant"],
		"准备 (zhǔnbèi)": ["unprepared", "prepared", "ready"],
		"没准备 (méi zhǔnbèi)": ["prepared", "unprepared", "unready"],
		"结束 (jiéshù)": ["begin", "end", "finish"],
		"开始 (kāishǐ)": ["end", "begin", "start"],
		"对 (duì)": ["correct", "right", "toward"],
		"错 (cuò)": ["right", "correct", "wrong"],
	}

var word_lists = [beginner_words, intermediate_words, advanced_words]
	


func get_random():
	var rand_difficulty
	if Global.user_prefs["difficulty"] > 0:
		rand_difficulty = randi()%Global.user_prefs["difficulty"]
	else:
		rand_difficulty = 0

	var current_question = word_lists[rand_difficulty].keys().pick_random()
	var responses = word_lists[rand_difficulty][current_question]
	
	var returnDict = {}
	returnDict[current_question] = responses
	return returnDict
